name = "pokedbots-scheduler"
main = "pokedbots-scheduler.js"
compatibility_date = "2024-01-01"

[triggers]
crons = [
  "*/15 * * * *",
  "30 5,11,17,23 * * *",
  "15 6,12,18,0 * * *",
  "5-59/15 * * * *"
]
